name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [20]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - run: sudo npm i -g pkg
      - run: npm ci


      - name: Set up QEMU
        run: |
          sudo apt update
          sudo apt install --reinstall -y qemu-user-static

      - name: Install ldid
        run: |
          sudo wget https://github.com/jesec/ldid-static/releases/download/v2.1.4/ldid-amd64 -O /usr/local/bin/ldid
          sudo chmod +x /usr/local/bin/ldid

      - run: npm run build-pkg
      - run: git fetch origin ${{ github.ref }}
      - run: git for-each-ref ${{ github.ref }} --format="%(contents)" > body

      - name: Rename linuxstatic to linux
        run: |
          mv dist-pkg/flood-linuxstatic-x64 dist-pkg/flood-linux-x64
          mv dist-pkg/flood-linuxstatic-arm64 dist-pkg/flood-linux-arm64

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body_path: body
          files: |
            dist-pkg/flood-linux-x64
            dist-pkg/flood-linux-arm64
            dist-pkg/flood-macos-x64
            dist-pkg/flood-macos-arm64
            dist-pkg/flood-win-x64.exe
            dist-pkg/flood-win-arm64.exe
